### ISSUE TITLE
About doomsday_fuel challenge

### ISSUE THREAD

**Issue by kazougen** [ivanseed/google-foobar-help#1]
Do you know any special input for the challenge ?
I use same method as you and I don't think my calculation is wrong because I got right answers for all the test cases except the 6th.
Now I got stuck, dont know what is wrong in my program.

**Comment by ivanseed** [comment]
It could be an edge case like a 1x1 matrices or 2x2.

Here is a really good tip for trying to figure out what your inputs are;

If you try and call `System.out` you will get an error - but you only get this error if the line is hit on run time, not compile time. So what you can do is to debug the input by wrapping System calls in input checks. Now this isn't useful yet because you won't know which test caused it to fail as you don't see the test output but there is a work around.

First, try doing `if input.length > 1000 then return null`. This will obviously cause all tests with input of over 1000 to fail, and you can visually see which tests pass and fail. Keep playing with this to see if you can get all tests passing expect test 6 which still fails. I.e. `if input.length == 1 then return null`, all tests pass expect one... This could be the potential input.

Then to verify if it was the right input try putting a System call inside the statement - __If you get an error now you know you have found the input you are failing on and you know exactly what the input is.__

Kind of hard to explain but I hope you get me, this way you know exactly what the input is and you can work out what the problem is. I had a similar problem and it turned out there was a case where the terminal state is the starting state.

**Comment by kazougen** [comment]
The case where the terminal state is the starting state, I figured it out and it is the 4th case. There probably is a bug in my program.
Thanks for your help, I'll try the tip and tell you soon

**Comment by kazougen** [comment]
I have found a bug, there is a mistake in calculating lcm of a list of numbers, too silly of me, lol :D
anw I know exactly the whole input matrix thanks to you. Thank you, again
