### ISSUE TITLE
How do you calculate inverse of matrix with fractions?

### ISSUE THREAD

**Issue by mehtasagar** [ivanseed/google-foobar-help#17]
I ma trying to follow the method given here. To calculate inverse  of the matrix, what approach should I follow to maintain the output in Fractions of integers as given in post. Let me know if you need more details?

**Comment by franklinvp** [comment]
You shouldn't compute the inverse matrix (I-Q)^{-1} as suggested here.  That is not efficient. Since the final goal is to compute (I-Q)^{-1}R what you should do is compute the columns of this matrix. The i-th column of this matrix is the solution X_i of the system (I-Q)X_i = R_i, where R_i is the i-th column of R and X_i is a column vector. To solve these systems of equations, you better first factor I-Q in LU decomposition. This is, a product of a lower triangular matrix L and an upper triangular matrix. Then for each system LUX_i=R_i you only need to do back substitution with L and forward substitution for U. Search how to do LU decomposition and implement it for fractions, if some library doesn't have it already. In most places they will have it implemented for floating point.

**Comment by franklinvp** [comment]
I did a Python implementation [here](https://github.com/franklinvp/foobar/blob/master/extra_challenge3_absorbing_probabilities.py), with plenty of comments. The LU and back/forth-substitution are the same as the Wikipedia page above, but written to use fractions instead of doubles.
