### ISSUE TITLE
Two-layer Dijkstra solution for prepare_the_bunnies_escape

### ISSUE THREAD

**Issue by LeeroyDing** [ivanseed/google-foobar-help#4]
I found the solution for this problem a bit too slow (there can be 20*20 nodes and the solution is actually at least `O(V^3)` where `V=w*h`) and might give wrong result (not really sure). After passing the test, I'd like to share my solution.

It's actually pretty simple - you need to duplicate the original maze. Let's call the original maze `M0` and the duplicate `M1` (as the second layer). On top of all the other edges, for each wall in `M0`, between `P0` and `P1`, you create a one-way edge of cost `1` from `P0` into the corresponding `P1'` in `M1`, which is in the same position as `P1` in `M0`. This step makes traveling from `M0` to `M1` break **exactly one** wall. Then you only need to get the smaller one between _the distance from the entrance of `M0` to the exit of `M0` (didn't break wall)_ and _the distance from the entrance of `M0` to the exit of `M1` (break one wall)_.

There are ways to make it easier to implement but the second layer is the key.

**Comment by ivanseed** [comment]
Sorry for the late reply.

Yeah your way is certainly more efficient and more elegant, my solution should be fast enough to pass the test cases but realistically `O(N^2)` is always going to be the preferred way. I think the only other improvement would be using A* to calculate the paths rather than Dijkstra.

If you wish to share with others feel free to create a PR with your improvement feel free - but I understand if you do not want to make it too easy for others ;)

**Comment by sreetamdas** [comment]
Hey @LeeroyDing , I'm currently on this problem, and I like your approach to it.
If you could explain it a bit more, it'd be great!

**Comment by LeeroyDing** [comment]
@sreetamdas it's already making the problem very simple by giving all the hints... Draw a picture of the two mazes and you should be able to figure it out ;)
